---
development:
  cloud_name: dbwtytrfc
  api_key: '519758747641278'
  api_secret: bfQAZE_0L_lh-6CfcaI4q9rDSmA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dbwtytrfc
  api_key: '519758747641278'
  api_secret: bfQAZE_0L_lh-6CfcaI4q9rDSmA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dbwtytrfc
  api_key: '519758747641278'
  api_secret: bfQAZE_0L_lh-6CfcaI4q9rDSmA
  enhance_image_tag: true
  static_image_support: false
